"""added address column to turf table

Revision ID: 34ed570ed10c
Revises: 408567ee87cb
Create Date: 2026-02-23 12:33:45.080866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ed570ed10c'
down_revision = '408567ee87cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turf', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
