"""empty message

Revision ID: 408567ee87cb
Revises: 59021572cdde
Create Date: 2026-02-15 20:49:04.325418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408567ee87cb'
down_revision = '59021572cdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_slot_per_time', ['turf_id', 'date', 'start_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.drop_constraint('unique_slot_per_time', type_='unique')

    # ### end Alembic commands ###
