"""add refund support to booking

Revision ID: 4353b72f773f
Revises: 5bd154e87e0c
Create Date: 2026-02-07 19:05:22.596390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4353b72f773f'
down_revision = '5bd154e87e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_refund_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('refunded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('refunded_at')
        batch_op.drop_column('stripe_refund_id')

    # ### end Alembic commands ###
