"""empty message

Revision ID: 59021572cdde
Revises: 95b33fef5698
Create Date: 2026-02-15 17:51:09.248121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59021572cdde'
down_revision = '95b33fef5698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('final_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('is_holiday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_weekend', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.drop_column('is_weekend')
        batch_op.drop_column('is_holiday')
        batch_op.drop_column('final_price')
        batch_op.drop_column('base_price')

    # ### end Alembic commands ###
