"""add turf facilities

Revision ID: 9da58186bb4e
Revises: 4353b72f773f
Create Date: 2026-02-08 12:07:43.756346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da58186bb4e'
down_revision = '4353b72f773f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floodlights', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wifi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('restrooms', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('refreshments', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turf', schema=None) as batch_op:
        batch_op.drop_column('refreshments')
        batch_op.drop_column('restrooms')
        batch_op.drop_column('wifi')
        batch_op.drop_column('parking')
        batch_op.drop_column('floodlights')

    # ### end Alembic commands ###
