"""add turf details fields

Revision ID: a4b2778b8715
Revises: 34ed570ed10c
Create Date: 2026-02-23 19:51:48.397560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b2778b8715'
down_revision = '34ed570ed10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('closing_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('surface_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('player_capacity', sa.String(length=50), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turf', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('player_capacity')
        batch_op.drop_column('width')
        batch_op.drop_column('length')
        batch_op.drop_column('surface_type')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('closing_time')
        batch_op.drop_column('opening_time')

    # ### end Alembic commands ###
